export const INSTITUTION_FORM = "INSTITUTION_FORM";
export const USER_FORM = "USER_FORM";
export const ITEM_ADD_FORM = "ITEM_ADD_FORM";
export const ITEM_MODIFY_FORM = "ITEM_MODIFY_FORM";
export const ADVICE_ITEM = "ADVICE_ITEM";
